/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include <EXTI_driver.h>
#include <gpio_driver.h>
#include <stm32f103x6.h>
int main(void)
{
	RCC_GPIOB_CLK_EN();
	RCC_GPIOC_CLK_EN();
	RCC_GPIOD_CLK_EN();
	RCC_AFIO_CLK_EN();
	GPIO_PinConfig_t pincon;
	pincon.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	pincon.GPIO_Output_Speed = GPIO_SPEED_10_MHZ;
	pincon.GPIO_PinNumber = pin3;
	MCAL_GPIO_INIT(GPIOB, &pincon);

	EXTI_S pin ;
	pin.EXTI_PIN = pin4;
	pin.EXTI_PORT = GPIOA;
	pin.TRIGER_STATE = triger_rising_and_falling ;
	MCAL_EXTI_INIT(&pin);
    /* Loop forever */
	for(;;);
}
void EXTI4_IRQHandler()
{
	MCAL_GPIO_TOGGLEPIN(GPIOB, pin3);
	EXTI_PENDING_PIN4_DIS;
}
