/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stm32f103x6.h>
#include <uart_driver.h>
#include <gpio_driver.h>
#include "../stm32f103x6_drivers/gpio_driver.c"
#include <EXTI_driver.h>
#include <stdint.h>
#include <stdlib.h>
uint8_t data ;
int main(void)
{
//	UART_CONF cnf;
//	cnf.Baud_Rate = UART_BAUD_RATE_115200;
//	cnf.Length =UART_DATA_BITS_9 ;
//	cnf.IRQ_Enable = UART_IRQ_EN_NONE;
//	cnf.Parity = UART_BARITY_EVEN;
//	cnf.Stop_Bits = UART_STOP_BITS_1;
//	cnf.USART_MODE = UART_MODE_RX_TX;
//	cnf.USARTx = USART1 ;
//	cnf.hwFlowCtl = UART_flow_ctl_NON;
//	mcal_uart_init(&cnf);
//	mcal_uart_pin_init(USART1);
//	mcal_uart_send_data(data, USART1);



	GPIO_PinConfig_t pinconf;
	pinconf.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	pinconf.GPIO_Output_Speed = GPIO_SPEED_50_MHZ;
	pinconf.GPIO_PinNumber = pin9;
	MCAL_GPIO_INIT(GPIOA, &pinconf);
	MCAL_GPIO_WRITEPIN(GPIOA, pin9, 1);
	while(1)
	{

	}
}
